services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}       # Aquí es donde se usa DB_ROOT_PASSWORD
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb

  laravel:
    image: bitnami/laravel:latest
    container_name: laravel
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - LARAVEL_DATABASE_HOST=mariadb
      - LARAVEL_DATABASE_PORT=3306
      - LARAVEL_DATABASE_NAME=${DB_DATABASE}
      - LARAVEL_DATABASE_USER=${DB_USERNAME}
      - LARAVEL_DATABASE_PASSWORD=${DB_PASSWORD}
      - LARAVEL_SKIP_SEEDING=true
    command: php artisan serve --host=0.0.0.0 --port=8000

volumes:
  mariadb_data:
